### ISSUE TITLE
Error for certain scripts (CADILAHC)

### ISSUE THREAD

**Issue by frroossst** [frroossst/StocksDataCollectionSystem#1]
>Traceback (most recent call last):
  File "auto.py", line 72, in <module>
    import scraper
  File "/home/home/Desktop/Projects/StocksDataCollectionSystem/scraper.py", line 404, in <module>
    main(auto=True)
  File "/home/home/Desktop/Projects/StocksDataCollectionSystem/scraper.py", line 353, in main
    T.getRSI(symbol,dataF)
  File "/home/home/Desktop/Projects/StocksDataCollectionSystem/scraper.py", line 225, in getRSI
    lastDataF = dataF.iloc[-1]
  File "/home/home/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/home/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1520, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/home/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1452, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

**Comment by frroossst** [comment]
The above occurs as a ticker in this case **CADILAHC** was delisted, simply remove it from the .json file that `scraper.py` is reading from. To confirm delisting try looking for the ticker in [yahoo finance](https://finance.yahoo.com/) or [google finance](https://www.google.com/finance/)

**Comment by frroossst** [comment]
The above occurs as a ticker in this case **CADILAHC** was delisted, simply remove it from the .json file that `scraper.py` is reading from. To confirm delisting try looking for the ticker in [yahoo finance](https://finance.yahoo.com/) or [google finance](https://www.google.com/finance/)
